// Independent HWP-v0 public attestation verifier (class V).
// Does not execute the behavioural algorithm; rejects mandatory disclosed mode.
// No Python dependency, no network access, no bundle-selected code execution.
import fs from 'node:fs';
import crypto from 'node:crypto';
import {pathToFileURL} from 'node:url';
const MAX=64*1024*1024, SAFE=BigInt(Number.MAX_SAFE_INTEGER);
export const hash=b=>crypto.createHash('sha256').update(b).digest();
const cat=(...v)=>Buffer.concat(v), hex=b=>b.toString('hex');
const need=(b,m='invalid')=>{if(!b)throw Error(m);};
const bytes=(b,n=null)=>{need(Buffer.isBuffer(b)&&b.length<=MAX&&(n===null||b.length===n),'bytes');return b;};
const integer=(n,lo=0,hi=Number.MAX_SAFE_INTEGER)=>{need(typeof n==='number'&&Number.isSafeInteger(n)&&n>=lo&&n<=hi,'integer');return n;};
export class Tag{constructor(n,v){this.n=n;this.v=v;}}
function head(m,n){n=BigInt(n);need(n>=0n&&n<1n<<64n);if(n<24n)return Buffer.from([m*32+Number(n)]);for(const [a,w] of [[24,1],[25,2],[26,4],[27,8]])if(n<1n<<BigInt(8*w)){let x=n,b=Buffer.alloc(1+w);b[0]=m*32+a;for(let i=w;i;i--){b[i]=Number(x&255n);x>>=8n;}return b;}throw Error('integer');}
export function enc(x,d=0){need(d<=32);if(x===null)return Buffer.from([246]);if(x===false)return Buffer.from([244]);if(x===true)return Buffer.from([245]);
 if(typeof x==='number'||typeof x==='bigint'){if(typeof x==='number')need(Number.isSafeInteger(x));let n=BigInt(x);need(n>=-(1n<<63n)&&n<(1n<<64n));return n>=0?head(0,n):head(1,-1n-n);}
 if(Buffer.isBuffer(x)){bytes(x);return cat(head(2,x.length),x);}
 if(typeof x==='string'){let b=Buffer.from(x,'utf8');need(new TextDecoder('utf-8',{fatal:true}).decode(b)===x);return cat(head(3,b.length),b);}
 if(Array.isArray(x)){need(x.length<=100000);return cat(head(4,x.length),...x.map(v=>enc(v,d+1)));}
 if(x instanceof Map){need(x.size<=100000);let pairs=[...x].map(([k,v])=>{need(['string','number','bigint'].includes(typeof k));return [enc(k,d+1),enc(v,d+1)];}).sort((a,b)=>Buffer.compare(a[0],b[0]));return cat(head(5,pairs.length),...pairs.flat());}
 if(x instanceof Tag){need(x.n===18);return cat(Buffer.from([210]),enc(x.v,d+1));}throw Error('type');}
export function dec(raw){bytes(raw);let off=0,seen=0;const take=n=>{integer(n,0,raw.length-off);let b=raw.subarray(off,off+n);off+=n;return b;};
 function parse(d){need(d<=32&&++seen<=100000,'cbor-budget');let f=take(1)[0],m=f>>5,a=f&31;if(m===7){need([20,21,22].includes(a));return a===20?false:a===21?true:null;}need(a<=27);let n=BigInt(a);if(a>=24){n=0n;for(let b of take(2**(a-24)))n=n*256n+BigInt(b);need(n>=(a===24?24n:1n<<BigInt(8*2**(a-25))),'nonminimal');}
 const scalar=v=>v>=-SAFE&&v<=SAFE?Number(v):v;
 if(m===0)return scalar(n);if(m===1){need(n<(1n<<63n));return scalar(-1n-n);}need(n<=SAFE);let k=Number(n);
 if(m===2)return take(k);if(m===3)return new TextDecoder('utf-8',{fatal:true}).decode(take(k));
 if(m===4){need(k<=100000);return Array.from({length:k},()=>parse(d+1));}
 if(m===5){need(k<=100000);let result=new Map(),prev=null;for(let i=0;i<k;i++){let start=off,key=parse(d+1),kb=raw.subarray(start,off);need(['string','number','bigint'].includes(typeof key));need(!result.has(key)&&(!prev||Buffer.compare(prev,kb)<0));prev=kb;result.set(key,parse(d+1));}return result;}
 need(m===6&&k===18);return new Tag(18,parse(d+1));}
 const out=parse(0);need(off===raw.length&&enc(out).equals(raw),'canonical-cbor');return out;}
const eq=(a,b)=>enc(a).equals(enc(b));
function fields(x,s){need(x instanceof Map&&eq([...x.keys()].sort(),s.split(' ').sort()),'fields');}
function typed(x,t,s){fields(x,'v type '+s);need(x.get('v')==='hwp/0'&&x.get('type')===t,'version/type');}
const reference=x=>{fields(x,'sha256 size');bytes(x.get('sha256'),32);integer(x.get('size'),0,MAX);return hex(x.get('sha256'));};
const refs=(a,min=0,max=4096)=>{need(Array.isArray(a)&&a.length>=min&&a.length<=max);let last='';for(let r of a){const h=reference(r);need(h>last);last=h;}return a;};
const ordered=(a,min=1,max=4096)=>{need(Array.isArray(a)&&a.length>=min&&a.length<=max&&a.every(x=>typeof x==='string'&&x.length));for(let i=1;i<a.length;i++)need(Buffer.compare(Buffer.from(a[i-1]),Buffer.from(a[i]))<0);};
const refraw=b=>new Map([['sha256',hash(b)],['size',b.length]]);
const includes=(a,x)=>a.some(v=>eq(v,x));
// Strict canonical prime-order Ed25519 point checking, beyond crypto.verify's policy.
const P=(1n<<255n)-19n,L=(1n<<252n)+27742317777372353535851937790883648493n;
const mod=x=>(x%P+P)%P;
function pow(a,n){let r=1n;for(a=mod(a);n;n>>=1n,a=mod(a*a))if(n&1n)r=mod(r*a);return r;}
const D=mod(-121665n*pow(121666n,P-2n)),I=pow(2n,(P-1n)/4n);
const le=b=>{let n=0n;for(let i=b.length-1;i>=0;i--)n=n*256n+BigInt(b[i]);return n;};
function add(p,q){let [x,y,z,t]=p,[X,Y,Z,T]=q,a=mod((y-x)*(Y-X)),b=mod((y+x)*(Y+X)),cc=mod(2n*D*t*T),d=mod(2n*z*Z),e=mod(b-a),f=mod(d-cc),g=mod(d+cc),h=mod(b+a);return [mod(e*f),mod(g*h),mod(f*g),mod(e*h)];}
const pointCache=new Map();
function point(b){bytes(b,32);let key=hex(b);if(pointCache.has(key))return pointCache.get(key);let n=le(b),sign=n>>255n,y=n&((1n<<255n)-1n),ok=false;
 if(y<P){let den=mod(D*y*y+1n);if(den){let x2=mod((y*y-1n)*pow(den,P-2n)),x=pow(x2,(P+3n)/8n);if(mod(x*x)!==x2)x=mod(x*I);if(mod(x*x)===x2&&!(x===0n&&sign)){if((x&1n)!==sign)x=P-x;if(!(x===0n&&y===1n)){let p=[x,y,1n,mod(x*y)],q=[0n,1n,1n,0n];for(let z=L;z;z>>=1n,p=add(p,p))if(z&1n)q=add(q,p);ok=q[0]===0n&&mod(q[1]-q[2])===0n;}}}}
 if(pointCache.size>8192)pointCache.clear();pointCache.set(key,ok);return ok;}
function keyParse(raw){const k=dec(raw);need(k instanceof Map&&k.size===4&&[1,3,-1,-2].every(i=>k.has(i)));need(k.get(1)===1&&k.get(3)===-19&&k.get(-1)===6&&point(k.get(-2)));return k.get(-2);}
function jsonDomain(x,d=0){need(d<=32);if(x===null||typeof x==='boolean'||typeof x==='string')return;if(typeof x==='number'){integer(x,-Number.MAX_SAFE_INTEGER);return;}if(Array.isArray(x)){for(let v of x)jsonDomain(v,d+1);return;}need(x instanceof Map&&[...x.keys()].every(k=>typeof k==='string'));for(let v of x.values())jsonDomain(v,d+1);}
function asciiJsonSize(x){if(x===null)return 4;if(typeof x==='boolean')return x?4:5;if(typeof x==='number')return String(x).length;if(typeof x==='string'){let n=2;for(let i=0;i<x.length;i++){let k=x.charCodeAt(i);n+=k>=127||k<32?([8,9,10,12,13].includes(k)?2:6):(k===34||k===92?2:1);}return n;}if(Array.isArray(x))return 2+Math.max(0,x.length-1)+x.reduce((n,v)=>n+asciiJsonSize(v),0);need(x instanceof Map);return 2+Math.max(0,x.size-1)+[...x].reduce((n,[k,v])=>n+asciiJsonSize(k)+1+asciiJsonSize(v),0);}
const ASS=['complete-document-observation','faithful-device-origin','faithful-monotonic-order','native-delivery-binding','no-hidden-prediction','precommitted-release','single-finalization'].sort();
const ROLES=['adaptive','annotation','calibration','capture','heldout','reproducibility'].sort();
const SPACE=new Set([...'\t\n\v\f\r \u0085\u00a0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u2028\u2029\u202f\u205f\u3000']);
const profiles=['keyboard','touch-tap','ime','gesture'],views=['birth','retained','layout','global'];
function modelCheck(m,features){jsonDomain(m);need(m instanceof Map);const keys=[...m.keys()].sort();need(eq(keys,['domains','features','purpose','version'])||eq(keys,['domains','features','purpose','training','version']));need(m.get('version')==='hwp-a-model/v0'&&m.get('purpose')==='validated-release'&&eq(m.get('features'),features));
 const domains=m.get('domains');need(domains instanceof Map&&domains.size>0&&domains.size<=128);
 function tree(t,d){need(t instanceof Map);if(t.has('value')){fields(t,'value');integer(t.get('value'),-1250,1250);}else{fields(t,'feature threshold left right');need(d<2);integer(t.get('feature'),0,178);integer(t.get('threshold'),-10000,10000);tree(t.get('left'),d+1);tree(t.get('right'),d+1);}}
 for(let [z,a] of domains){need(typeof z==='string'&&[...z].length<=256);let [p,path,lang,v,...rest]=z.split('|');need(!rest.length&&profiles.includes(p)&&path&&lang&&views.includes(v));fields(a,'heads scales prototypes support_calibration');const heads=a.get('heads');fields(heads,'transcription automation simulation mixed');for(let ts of heads.values()){need(Array.isArray(ts)&&ts.length===32);for(let t of ts)tree(t,0);}const scales=a.get('scales');need(Array.isArray(scales)&&scales.length===179);scales.forEach(n=>integer(n,500,20000));const ps=a.get('prototypes');need(Array.isArray(ps)&&ps.length>=1&&ps.length<=128);for(let pp of ps){need(Array.isArray(pp)&&pp.length===179);pp.forEach(n=>integer(n,-10000,10000));}let sc=a.get('support_calibration');need(Array.isArray(sc)&&sc.length<=100000);sc.forEach(n=>integer(n,0,1e9));}}

export function verifyAttested(raw,document,policyBytes,policyPin,definitionBytes,featureNames){
 try{bytes(document);bytes(policyPin,32);need(hash(policyBytes).equals(policyPin),'external-policy-pin');let po=dec(policyBytes);
 typed(po,'verification-policy','label releases capture_authorities evaluators quorum modes require_author identity_authorities denied status_as_of protocol purpose');need(['conformance','production'].includes(po.get('purpose')));need(typeof po.get('label')==='string'&&[...po.get('label')].length>=1&&[...po.get('label')].length<=256);refs(po.get('releases'));refs(po.get('evaluators'),0,64);integer(po.get('quorum'),1,64);ordered(po.get('modes'));need(po.get('modes').every(x=>['attested-v1','disclosed-v1'].includes(x)));need(typeof po.get('require_author')==='boolean');refs(po.get('identity_authorities'),0,64);if(po.get('status_as_of')!==null)integer(po.get('status_as_of'));
 const denied=po.get('denied');need(Array.isArray(denied));let pd='';for(let d of denied){bytes(d,32);need(hex(d)>pd);pd=hex(d);}const deniedSet=new Set(denied.map(hex));
 const cas=po.get('capture_authorities');need(Array.isArray(cas)&&cas.length<=64);let caLast='';for(let g of cas){fields(g,'profile keys');let h=reference(g.get('profile'));need(h>caLast);caLast=h;refs(g.get('keys'),1,64);}
 const bundle=dec(raw);typed(bundle,'bundle','root objects');let objects=new Map(),last='';const oo=bundle.get('objects');need(Array.isArray(oo)&&oo.length<=4096);for(let row of oo){need(Array.isArray(row)&&row.length===2);let [h,b]=row;bytes(h,32);bytes(b);need(hash(b).equals(h)&&hex(h)>last);last=hex(h);objects.set(last,b);}
 const get=r=>{let h=reference(r);need(!deniedSet.has(h)&&objects.has(h),'missing-or-denied-object');let b=objects.get(h);need(b.length===r.get('size')&&hash(b).equals(r.get('sha256')));return b;};
 const obj=r=>dec(get(r));const sigCache=new Map();
 function signed(r){let raw=get(r),rh=reference(r);if(sigCache.has(rh))return sigCache.get(rh);let e=dec(raw);need(e instanceof Tag&&e.n===18&&Array.isArray(e.v)&&e.v.length===4);let [pr,up,pay,sig]=e.v;bytes(pr);bytes(pay);bytes(sig,64);let prot=dec(pr);need(prot instanceof Map&&prot.size===3&&prot.get(1)===-19&&prot.get(3)==='application/cbor'&&prot.has(4));need(up instanceof Map&&up.size===0);let kid=bytes(prot.get(4),32),kh=hex(kid);need(!deniedSet.has(kh)&&objects.has(kh));let kr=objects.get(kh);need(hash(kr).equals(kid));const pub=keyParse(kr);need(point(sig.subarray(0,32))&&le(sig.subarray(32))<L);const key=crypto.createPublicKey({key:cat(Buffer.from('302a300506032b6570032100','hex'),pub),format:'der',type:'spki'});need(crypto.verify(null,enc(['Signature1',pr,Buffer.from('HWP/0'),pay]),key,sig),'signature');let body=dec(pay);need(body instanceof Map&&body.get('v')==='hwp/0');let out=[body,kh];sigCache.set(rh,out);return out;}
 const def=dec(definitionBytes),defref=refraw(definitionBytes);typed(def,'protocol-definition','name revision artifacts');need(def.get('name')==='Human Writing Protocol'&&def.get('revision')==='0.0.0');need(eq(po.get('protocol'),defref)&&get(defref).equals(definitionBytes),'protocol-pin');
 const da=def.get('artifacts');need(da instanceof Map);const fixedNames=JSON.parse(get(da.get('docs/FEATURE_NAMES.json')).toString('utf8'));need(eq(featureNames,fixedNames),'feature-names-pin');const relCache=new Map();
 const artifactKeys=['algorithm_spec','program','model','decision_policy','evidence_adapter','output_contract'];
 function release(r){get(r);let h=reference(r);if(relCache.has(h))return relCache.get(h);need(includes(po.get('releases'),r));let v=obj(r);typed(v,'release','algorithm claim artifacts capture_profiles protocol stage validation');need(v.get('algorithm')==='hwp-a/v0'&&eq(v.get('protocol'),defref)&&['fresh-composition','wording-origin'].includes(v.get('claim')));need(['conformance','empirical'].includes(v.get('stage')));need(po.get('purpose')!=='production'||v.get('stage')==='empirical','test-release-not-production');let ar=v.get('artifacts');fields(ar,artifactKeys.join(' '));for(let [k,rr]of ar){get(rr);if(['algorithm_spec','program','evidence_adapter','output_contract'].includes(k))need(eq(rr,da.get(k)),'uninstalled-computation');}for(let rr of da.values())get(rr);
 const pm=obj(ar.get('program'));typed(pm,'program','algorithm files');need(pm.get('algorithm')==='hwp-a/v0'&&Array.isArray(pm.get('files')));for(let f of pm.get('files')){fields(f,'path ref');get(f.get('ref'));}
 const model=obj(ar.get('model'));modelCheck(model,featureNames);need(asciiJsonSize(model)<=20000000,'model-size');const dp=obj(ar.get('decision_policy'));fields(dp,'threshold claim_kind allowed_domains');integer(dp.get('threshold'),-999999999,1e9);need(dp.get('claim_kind')===v.get('claim'));let dom=dp.get('allowed_domains');ordered(dom);let groups=new Map();for(let z of dom){need(model.get('domains').has(z));let [p,path,lang,view,...rest]=z.split('|');need(!rest.length&&profiles.includes(p)&&path&&lang&&views.includes(view));let g=[p,path,lang].join('|');if(!groups.has(g))groups.set(g,new Set());groups.get(g).add(view);}need([...groups.values()].every(s=>s.size===4));
 refs(v.get('capture_profiles'),1,32);let cps=new Map(),union=new Set();for(let rr of v.get('capture_profiles')){let cp=obj(rr);typed(cp,'capture-profile','class domains max_resolution_us assumptions evaluation');need(['fixture','evaluated'].includes(cp.get('class')));need(po.get('purpose')!=='production'||cp.get('class')==='evaluated');ordered(cp.get('domains'));integer(cp.get('max_resolution_us'),1,10000);need(eq(cp.get('assumptions'),ASS));for(let z of cp.get('domains')){let q=z.split('|');need(q.length===3&&profiles.includes(q[0])&&q[1]&&q[2]);union.add(z);}if(cp.get('class')==='evaluated')get(cp.get('evaluation'));else need(cp.get('evaluation')===null);cps.set(reference(rr),cp);}need([...groups.keys()].every(g=>union.has(g)));
 const ds=obj(v.get('validation'));typed(ds,'validation-dossier','stage claim model decision_policy program capture_profiles allowed_domains risk_target coverage_target confidence reports candidate');for(let k of ['stage','claim','capture_profiles'])need(eq(ds.get(k),v.get(k)));for(let k of ['model','decision_policy','program'])need(eq(ds.get(k),ar.get(k)));need(eq(ds.get('allowed_domains'),dom)&&eq(ds.get('risk_target'),[1,1000])&&eq(ds.get('coverage_target'),[1,2])&&eq(ds.get('confidence'),[19,20]));let rr=ds.get('reports');need(Array.isArray(rr));let roles=[];for(let x of rr){fields(x,'role artifact');need(ROLES.includes(x.get('role')));roles.push(x.get('role'));get(x.get('artifact'));}ordered(roles,0);need(eq(roles,v.get('stage')==='empirical'?ROLES:[]));if(v.get('stage')==='conformance')need(ds.get('candidate')===null);else{let ca=obj(ds.get('candidate'));typed(ca,'release','algorithm claim artifacts capture_profiles protocol stage validation');need(ca.get('stage')==='conformance');for(let k of ['algorithm','claim','artifacts','capture_profiles','protocol'])need(eq(ca.get(k),v.get(k)));let prior=obj(ca.get('validation'));typed(prior,'validation-dossier','stage claim model decision_policy program capture_profiles allowed_domains risk_target coverage_target confidence reports candidate');need(prior.get('stage')==='conformance'&&prior.get('candidate')===null&&eq(prior.get('reports'),[]));for(let k of ['claim','model','decision_policy','program','capture_profiles','allowed_domains','risk_target','coverage_target','confidence'])need(eq(prior.get(k),ds.get(k)));} let out={v,ar,dp,cps};relCache.set(h,out);return out;}
 const done=new Map(),active=new Set(),seenSessions=new Map();let count=0;
 function proof(r,expected=null){get(r);let h=reference(r);need(!active.has(h),'proof-cycle');if(done.has(h)){const q=done.get(h);if(expected)need(q.doc.equals(expected));return q;}need(++count<=64);active.add(h);let pr=obj(r);typed(pr,'proof','statement appraisals author');refs(pr.get('appraisals'),1,64);const st=obj(pr.get('statement'));typed(st,'statement','document media_type scope release captures target_capture lineage mode author nonce');const doc=get(st.get('document'));need(doc.length<=1048576);if(expected)need(doc.equals(expected));const text=new TextDecoder('utf8',{fatal:true}).decode(doc);need(['text/plain','text/markdown'].includes(st.get('media_type')));bytes(st.get('lineage'),32);bytes(st.get('nonce'),32);need(po.get('modes').includes(st.get('mode')));need(st.get('mode')==='attested-v1','unsupported-required-recomputation');const rel=release(st.get('release')),claim=rel.v.get('claim');refs(st.get('captures'),1,32);need(includes(st.get('captures'),st.get('target_capture')));
 const metas=new Map(),captureKeys=new Set(),localSessions=new Set();for(let cr of st.get('captures')){let [end,kid]=signed(cr);typed(end,'capture-end','start count root complete participation document');let [start,sk]=signed(end.get('start'));typed(start,'capture-start','session profile adapter nonce subject release parents');need(kid===sk);bytes(start.get('session'),32);bytes(start.get('nonce'),32);integer(end.get('count'),2,1000000);bytes(end.get('root'),32);reference(end.get('document'));need(end.get('complete')===true);need(includes(rel.v.get('capture_profiles'),start.get('profile'))&&eq(start.get('adapter'),rel.ar.get('evidence_adapter')));const grant=cas.find(g=>eq(g.get('profile'),start.get('profile')));need(grant&&grant.get('keys').some(k=>reference(k)===kid&&get(k).equals(objects.get(kid))));let original=release(start.get('release'));need(eq(original.ar.get('evidence_adapter'),rel.ar.get('evidence_adapter'))&&includes(original.v.get('capture_profiles'),start.get('profile')));if(eq(cr,st.get('target_capture'))){need(eq(start.get('release'),st.get('release')),'release-not-precommitted');need(eq(end.get('document'),st.get('document'))&&eq(start.get('subject'),st.get('author')));}
 const pair=kid+':'+hex(start.get('session'));need(!localSessions.has(pair));localSessions.add(pair);need(!seenSessions.has(pair)||seenSessions.get(pair)===reference(cr));seenSessions.set(pair,reference(cr));captureKeys.add(kid);
 if(start.get('subject')===null)need(end.get('participation')===null);else{keyParse(get(start.get('subject')));let [b,pk]=signed(end.get('participation'));typed(b,'participation','start');need(eq(b.get('start'),end.get('start'))&&pk===reference(start.get('subject'))&&pk!==kid);}
 let pars=start.get('parents');need(Array.isArray(pars)&&pars.length<=32);let prs=[];for(let pa of pars){fields(pa,'capture proof');reference(pa.get('capture'));prs.push(pa.get('capture'));if(pa.get('proof')!==null){let pp=obj(pa.get('proof'));typed(pp,'proof','statement appraisals author');need(eq(obj(pp.get('statement')).get('target_capture'),pa.get('capture')));}}refs(prs,0,32);metas.set(reference(cr),{ref:cr,start,end});}
 let reachable=new Set();function visit(cr,stack){const ch=reference(cr);need(!stack.has(ch)&&metas.has(ch)&&eq(metas.get(ch).ref,cr));if(reachable.has(ch))return;reachable.add(ch);let ss=new Set(stack);ss.add(ch);for(let x of metas.get(ch).start.get('parents'))visit(x.get('capture'),ss);}visit(st.get('target_capture'),new Set());need(reachable.size===metas.size,'unrelated-capture');
 const scope=obj(st.get('scope'));typed(scope,'scope','document kind ranges');need(eq(scope.get('document'),st.get('document')));need(['whole-document','selected-ranges'].includes(scope.get('kind')));let ranges=scope.get('ranges');need(Array.isArray(ranges)&&ranges.length>0&&ranges.length<=10000);let bounds=new Set([0]),n=0;for(let ch of text){n+=Buffer.byteLength(ch);bounds.add(n);}let endAt=0,meaningful=false,excluded=false,selected=[],prev=null;
 for(let rr of ranges){fields(rr,'start end origin');let a=integer(rr.get('start'),0,doc.length),b=integer(rr.get('end'),a+1,doc.length),o=rr.get('origin');need(a===endAt&&bounds.has(a)&&bounds.has(b));endAt=b;need(Array.isArray(o)&&o.length);if(prev){let z=prev.get('origin');need(!((o[0]!=='inherited'&&eq(o,z))||(o[0]===z[0]&&o[0]==='inherited'&&eq(o[1],z[1])&&z[3]===o[2])),'nonmaximal-scope');}prev=rr;
 if(o[0]==='excluded'){need(o.length===2&&typeof o[1]==='string'&&[...o[1]].length>=1&&[...o[1]].length<=1024);excluded=true;continue;}
 selected.push([a,b]);meaningful||=[...new TextDecoder('utf8',{fatal:true}).decode(doc.subarray(a,b))].some(ch=>!SPACE.has(ch));
 if(o[0]==='observed'){need(o.length===2);refs(o[1],1,32);for(let rr of o[1]){need(includes(st.get('captures'),rr));need(eq(metas.get(reference(rr)).start.get('subject'),st.get('author')));}}
 else{need(o[0]==='inherited'&&o.length===4&&claim==='wording-origin');let parent=proof(o[1]);let pa=integer(o[2],0,parent.doc.length),pb=integer(o[3],pa+1,parent.doc.length);need(pb-pa===b-a&&parent.doc.subarray(pa,pb).equals(doc.subarray(a,b)));let cur=pa;for(let [x,y]of parent.ranges){if(y<=cur)continue;if(x>cur)break;cur=Math.max(cur,y);if(cur>=pb)break;}need(cur>=pb);}}
 need(endAt===doc.length&&meaningful&&selected.length&&((scope.get('kind')==='whole-document')===!excluded));
 let evalKeys=new Set();for(let rr of pr.get('appraisals')){let [b,kid]=signed(rr);typed(b,'appraisal','statement result');need(eq(b.get('statement'),pr.get('statement'))&&b.get('result')==='HUMAN-WRITTEN');need(po.get('evaluators').some(r=>reference(r)===kid&&get(r).equals(objects.get(kid)))&&!evalKeys.has(kid)&&!captureKeys.has(kid));evalKeys.add(kid);}need(evalKeys.size>=po.get('quorum'));
 let author='none';if(st.get('author')===null)need(pr.get('author')===null&&!po.get('require_author'));else{keyParse(get(st.get('author')));let [b,kid]=signed(pr.get('author'));typed(b,'author-endorsement','statement identity');need(eq(b.get('statement'),pr.get('statement'))&&kid===reference(st.get('author'))&&!captureKeys.has(kid)&&!evalKeys.has(kid));author='pseudonymous-key-endorsement';if(b.get('identity')!==null){let [id,issuer]=signed(b.get('identity'));typed(id,'identity-binding','subject namespace identifier');need(po.get('identity_authorities').some(r=>reference(r)===issuer&&get(r).equals(objects.get(issuer)))&&eq(id.get('subject'),st.get('author')));for(let [k,max]of [['namespace',256],['identifier',1024]])need(typeof id.get(k)==='string'&&[...id.get(k)].length>=1&&[...id.get(k)].length<=max);author={kind:'attested-key-controller',namespace:id.get('namespace'),identifier:id.get('identifier')};}}
 let out={doc,ranges:selected,claim,scope:scope.get('kind'),author,document:st.get('document'),proof:r,release:st.get('release')};done.set(h,out);active.delete(h);return out;}
 let v=proof(bundle.get('root'),document);return {status:po.get('purpose')==='conformance'?'TEST-ONLY':'VALID-HWP',outcome:po.get('purpose')==='conformance'?'NOT PROVABLE':'HUMAN-WRITTEN',claim:v.claim,scope:v.scope,ranges:v.ranges,author:v.author,document:hex(v.document.get('sha256')),proof:hex(v.proof.get('sha256')),release:hex(v.release.get('sha256')),execution_checked:'attestation'};
 }catch(e){return {status:'NO-VALID-HWP',outcome:'NOT PROVABLE',reason:e.message,authorship_inference:null};}}

if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){
 const args=process.argv.slice(2),at=k=>args[args.indexOf(k)+1];
 if(args.length<7){console.error('Usage: node verify_attested.mjs proof.hwp --document text.txt --policy policy.cbor --policy-pin HEX');process.exit(2);}
 const def=Buffer.from(fs.readFileSync(new URL('../manifests/protocol.cbor.hex',import.meta.url),'utf8').trim(),'hex');
 const names=JSON.parse(fs.readFileSync(new URL('../docs/FEATURE_NAMES.json',import.meta.url),'utf8'));
 const out=verifyAttested(fs.readFileSync(args[0]),fs.readFileSync(at('--document')),fs.readFileSync(at('--policy')),Buffer.from(at('--policy-pin'),'hex'),def,names);
 console.log(JSON.stringify(out,null,2));process.exit(out.status==='NO-VALID-HWP'?1:out.status==='TEST-ONLY'?2:0);
}
